version: "3.7"
services:
  eng_tool_api:
    container_name: eng_tool_api_container
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=8080
    entrypoint: /start-reload.sh
    volumes:
      - ./api:/app
  eng_tool_ui:
    container_name: eng_tool_ui_container
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"

    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - eng_tool_api
    stdin_open: true

    # For package update use:
    #   docker-compose down -v
    #   docker-compose up -d --build
